Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      + C:\Users\Admin\Phishing-detection-platform\venv\Scripts\python.exe C:\Users\Admin\AppData\Local\Temp\pip-install-dss_xf4y\numpy_72094fa8633148ee9eba1295059deb3c\vendored-meson\meson\meson.py setup C:\Users\Admin\AppData\Local\Temp\pip-install-dss_xf4y\numpy_72094fa8633148ee9eba1295059deb3c C:\Users\Admin\AppData\Local\Temp\pip-install-dss_xf4y\numpy_72094fa8633148ee9eba1295059deb3c\.mesonpy-pd04pot0 -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=C:\Users\Admin\AppData\Local\Temp\pip-install-dss_xf4y\numpy_72094fa8633148ee9eba1295059deb3c\.mesonpy-pd04pot0\meson-python-native-file.ini
      The Meson build system
      Version: 1.2.99
      Source dir: C:\Users\Admin\AppData\Local\Temp\pip-install-dss_xf4y\numpy_72094fa8633148ee9eba1295059deb3c
      Build dir: C:\Users\Admin\AppData\Local\Temp\pip-install-dss_xf4y\numpy_72094fa8633148ee9eba1295059deb3c\.mesonpy-pd04pot0
      Build type: native build
      Project name: NumPy
      Project version: 1.26.4
      WARNING: Failed to activate VS environment: Could not parse vswhere.exe output

      ..\meson.build:1:0: ERROR: Unknown compiler(s): [['icl'], ['cl'], ['cc'], ['gcc'], ['clang'], ['clang-cl'], ['pgcc']]
      The following exception(s) were encountered:
      Running `icl ""` gave "[WinError 2] The system cannot find the file specified"
      Running `cl /?` gave "[WinError 2] The system cannot find the file specified"
      Running `cc --version` gave "[WinError 2] The system cannot find the file specified"
      Running `gcc --version` gave "[WinError 2] The system cannot find the file specified"
      Running `clang --version` gave "[WinError 2] The system cannot find the file specified"
      Running `clang-cl /?` gave "[WinError 2] The system cannot find the file specified"
      Running `pgcc --version` gave "[WinError 2] The system cannot find the file specified"

      A full log can be found at C:\Users\Admin\AppData\Local\Temp\pip-install-dss_xf4y\numpy_72094fa8633148ee9eba1295059deb3c\.mesonpy-pd04pot0\meson-logs\meson-log.txt
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.